### ISSUE TITLE
Tareas

### ISSUE THREAD

**Issue by Santiago-Restrepo** [JuanesGalvis/DigiNotaria#1]
Galvis:

-3
- 5
- 6
- 7
- 8
- 9
- Bienvenidos (11)
- 12
- 15
- 16
- 19
- 24
- 26
-27
- Pago trámite (28)
-31

Santi:

- 1
- 2
- Home (4)
- 10
- 13
- 14
- Iniciar sesión (17)
- Registro (18)
- 20
- 21
- 22
- 23
- 25
- 29
-30
-32

**Comment by Santiago-Restrepo** [comment]
Tareitas

**Comment by JuanesGalvis** [comment]
Terminadas [5-12]: 3, 5 (Las 6.7.8.9.12 son contenido de la 5 entonces ya están listas también), 11, 15 (Menú - para usarlo simplemente se usa: `include Menu.pug` ) y 16

**Comment by Santiago-Restrepo** [comment]
Terminadas[1,2,10,17,18] : Faltan en algunas meterles JS

**Comment by Santiago-Restrepo** [comment]
Terminadas [13, 14]: Home y home de invitado

**Comment by Santiago-Restrepo** [comment]
Terminada [4]: Perfil

**Comment by JuanesGalvis** [comment]
Terminada: 19, 24, 26, 27 y 28 (Pagos) -> Falta JavaScript para validaciones

**Comment by JuanesGalvis** [comment]
Terminado JS de Pagos y página 31 -> **Solo Falta enlazar las páginas**
